package com.permithub.enums;
public enum OutpassStatus { PENDING, MENTOR_APPROVED, PARENT_APPROVED, ADVISOR_APPROVED, WARDEN_APPROVED, AO_APPROVED, PRINCIPAL_APPROVED, REJECTED, CANCELLED, EXPIRED, RETURNED }
